### ISSUE TITLE
Update the MapML extension in the GeoServer community module build?

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/geoserver#24]
https://github.com/geoserver/geoserver/blob/master/doc/en/user/source/community/mapml/index.rst refers to the old bower component and the `<map>` built-in, can this be updated to use mapml-viewer instead?

**Comment by prushforth** [comment]
Thanks for the prod! We have updated the viewer in this repo,  (did that last November, actually).  There is an [OSGeo - OGC - ASF Code Sprint ](https://github.com/opengeospatial/joint-ogc-osgeo-asf-sprint-2021) next week and it's my goal to submit a PR upstream that updates the viewer and converts the MapML community module into an 'extension' module, which is a bit of a step up in terms of requirements, but also brings ancillary benefits such as being tested during continuous integration (community modules are not so tested).
